spring.datasource.url=jdbc:postgresql://ep-delicate-dawn-aibg6ira-pooler.c-4.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_ItBDoHYZ6l4N&sslmode=require&channelBinding=require
spring.jpa.hibernate.ddl-auto=update

# FreeMarker config
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftlh
spring.freemarker.cache=false

# Log SQL queries (comment out to silence)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
